import { createRoot } from 'react-dom/client'
import { useRoute, useLocation } from 'wouter'
import './styles.css'
import { Logo } from '@pmndrs/branding'
import { App } from './App'

import { BrowserRouter as Router, Route, Routes } from 'react-router-dom'
import LandingPage from './LandingPage'

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

function Root() {
  // get location coordinates here
  let userLocation
  if (navigator.geolocation) {
    userLocation = navigator.geolocation.getCurrentPosition(showPosition, handleError)
  } else {
    console.error('Geolocation is not supported by this browser.')
  }

  function showPosition(position) {
    const latitude = position.coords.latitude
    const longitude = position.coords.longitude
    console.log('Latitude:', latitude, 'Longitude:', longitude)
  }
  function handleError(error) {
    switch (error.code) {
      case error.PERMISSION_DENIED:
        console.error('User denied the request for Geolocation.')
        break
      case error.POSITION_UNAVAILABLE:
        console.error('Location information is unavailable.')
        break
      case error.TIMEOUT:
        console.error('The request to get user location timed out.')
        break
      case error.UNKNOWN_ERROR:
        console.error('An unknown error occurred.')
        break
    }
  }

  // starts pendo tracking
  window.pendo.initialize({
    visitor: {
      id: '<visitor-id-goes-here>',
      email: '<email-goes-here>',
      userPermissions: '<user-permissions-goes-here>'
    },

    account: {
      id: '<account-id-goes-here>',
      accountName: '<account-name-goes-here>',
      payingStatus: '<paying-status-goes-here>',
      location: userLocation,
      accountValue: '<account-value-goes-here>'
    }
  })
  console.log('pendo init')

  const [, params] = useRoute('/item/:id')
  const [, setLocation] = useLocation()
  console.log('params: ', params)
  return (
    <>
      <Router>
        <Routes>
          <Route path="/" element={<LandingPage />} />
          <Route path="/demo" element={<App />} />
        </Routes>
      </Router>
      <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }}>
        <a href="https://pmnd.rs/" style={{ position: 'absolute', bottom: 40, left: 90, fontSize: '13px' }}>
          pmnd.rs
          <br />
          dev collective
        </a>
        <div style={{ position: 'absolute', bottom: 40, right: 40, fontSize: '13px' }}>15/06/2023</div>
        <Logo style={{ position: 'absolute', bottom: 40, left: 40, width: 30 }} />
        <a style={{ position: 'absolute', top: 30, left: 30, fontSize: '13px' }} href="/demo" onClick={() => setLocation('/demo')}>
          {params ? '< back' : 'double click to enter portal'}
        </a>
        <a style={{ position: 'absolute', top: 30, left: '80vw', fontSize: '100px', color: '#ff8400' }} href="#" onClick={() => setLocation('/')}>
          {params === null ? (
            <span>
              <img src="./ZappyLogo.png" alt="" style={{ width: '20rem' }} />
            </span>
          ) : (
            ''
          )}
          {params !== null && params.id === '01' ? <span>Blue Lacy</span> : ''}
          {params !== null && params.id === '02' ? <span>Lucky Duck</span> : ''}
          {params !== null && params.id === '03' ? <span>ATX Cocina</span> : ''}
          {params !== null && params.id === '04' ? <span>Bar Moxy</span> : ''}
          {params !== null && params.id === '05' ? <span>Hank's</span> : ''}
          {params !== null && params.id === '06' ? <span>Saturn</span> : ''}
          {params !== null && params.id === '07' ? (
            <span>
              <img src="./ZappyLogo.png" alt="" style={{ width: '20rem' }} />
            </span>
          ) : (
            ''
          )}
          {params !== null && params.id === '08' ? (
            <span>
              <img src="./ZappyLogo.png" alt="" style={{ width: '20rem' }} />
            </span>
          ) : (
            ''
          )}
          {params !== null && params.id === '09' ? (
            <span>
              <img src="./ZappyLogo.png" alt="" style={{ width: '20rem' }} />
            </span>
          ) : (
            ''
          )}
        </a>

        <a style={{ position: 'absolute', bottom: 30, left: 30, fontSize: '13px' }} href="#" onClick={() => setLocation('/item/01')}>
          {params !== null && params.id === '01' ? (
            <>
              <div className="card-container">
                {/* Blue Lacy */}
                {/* https://www.zappyhour.co/happy-hour-details?recordId=recn53pSPpCoZTZ1m */}
                <div className="left-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Happy Hour Drink Specials</span>
                      <li>$5 House Wines</li>
                      <li>$3 off Topshelf Liquor</li>
                      <li>$2 off Draft Beer</li>
                      <li>$1 off Bottled and Canned Beer</li>
                      <li>$4 Dog Food</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Daily Specials</span>
                      <li>Monday: $4 Well Liquor</li>
                      <li>Tuesday: $2 off all Cocktails</li>
                      <li>Wednesday: $2 off Glasses of Wine, ½ off Bottles of Wine</li>
                      <li>Thursday: 12 off Draft Beer, ½ off Dog Treats</li>
                      <li>Friday: $4 Fireball, $4 Fireman's 4 Bottles</li>
                    </ul>
                  </div>
                </div>

                <div className="right-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Happy Hour Times</span>
                      <li>Monday - Friday: 4:00pm - 7:00pm</li>
                      <li>Sunday: 7:00am - 4:00pm</li>
                    </ul>
                  </div>
                </div>
              </div>
            </>
          ) : (
            ''
          )}
        </a>

        <a style={{ position: 'absolute', bottom: 30, left: 30, fontSize: '13px' }} href="#" onClick={() => setLocation('/item/02')}>
          {params !== null && params.id === '02' ? (
            <>
              <div className="card-container">
                {/* https://www.zappyhour.co/happy-hour-details?recordId=rec1kkOwy5hUam6hd */}
                <div className="left-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Happy Hour Times</span>
                      <li>Monday - Thursday: 6pm - 8pm</li>
                      <li>Friday: 4pm - 8pm</li>
                      <li>Saturday & Sunday: 12pm - 8pm</li>
                      <li>Sundays (Industry Night) from 8pm - 12am</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Happy Hour Drink Specials</span>
                      <li>$2 Keystone</li>
                      <li>$2 Miller Highlife</li>
                      <li>$5 Titos</li>
                      <li>$5 Espolon</li>
                      <li>$5 Jameson</li>
                      <li>$5 Espolon</li>
                    </ul>
                  </div>
                </div>

                <div id="right-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Happy Hour Food Specials</span>
                      <li>Mondays, 6pm - 12am (while supplies last): Half-priced chicken sandwiches</li>
                      <li>Tuesdays, 6pm-2am: Half off appetizers</li>
                      <li>Wednesdays, 6pm-2am: $1 wings</li>
                      <li>Thursdays, 6pm - 2am (while supplies last): $5 burger and fries</li>
                    </ul>
                  </div>

                  <div className="card">
                    <ul>
                      <span className="cardTitle">Days w/Specials</span>
                      <li>Mon</li>
                      <li>Tue</li>
                      <li>Wed</li>
                      <li>Thu</li>
                      <li>Fri</li>
                      <li>Fri</li>
                      <li>Sat</li>
                      <li>Sun</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Types of Specials</span>
                      <li>🍗</li>
                      <li>🍺</li>
                      <li>🍸</li>
                    </ul>
                  </div>

                  <div className="card">
                    <ul>
                      <span className="cardTitle">Sources (as of June 23, 2024)</span>
                      <li>Website https://atx.luckyducktx.com/</li>
                      <li>Google Maps https://maps.app.goo.gl/HNU7NNgBTqzcjC7t5</li>
                      <li>Yelp https://www.yelp.com/biz/the-lucky-duck-austin</li>
                    </ul>
                  </div>
                </div>
              </div>
            </>
          ) : (
            ''
          )}
        </a>

        <a style={{ position: 'absolute', bottom: 30, left: 30, fontSize: '13px' }} href="#" onClick={() => setLocation('/item/03')}>
          {params !== null && params.id === '03' ? (
            <>
              <div className="card-container">
                <div className="left-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">BEBIDAS</span>
                      <li>MARGARITA DE LA CASA 10 lunazul blanco, lime, agave</li>
                      <li>MEZCAL PALOMA 10 rosaluna, grapefruit, lime, lady bird grapefruit</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">COMIDAS</span>
                      <li>GUACAMOLE 9 serrano, onion, herbs, olive oil, lime</li>
                      <li>TACOS DE PESCADO 9 morita blackened, chipotle aioli, pickled cabbage, sesame</li>
                      <li>TACOS DE PUERCO 9 carnitas, salsa verde, cilantro, onion</li>
                      <li>TAMAL 9 acorn squash masa, seared calabacita, cilantro salad</li>
                    </ul>
                  </div>
                </div>

                <div className="right-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">HAPPY HOUR</span>
                      <li>MON-THURS 5-6PM</li>
                      <li>FRI-SUN 4-5PM</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Days w/Specials</span>
                      <li>Mon</li>
                      <li>Tue</li>
                      <li>Wed</li>
                      <li>Thu</li>
                      <li>Fri</li>
                      <li>Sat</li>
                      <li>Sun</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Sources</span>
                      <li>
                        Website: <a href="https://www.atxcocina.com/">ATX Cocina</a>
                      </li>
                      <li>
                        Google Maps: <a href="https://maps.app.goo.gl/nyeA18Mrgh5yQordA">Google Maps</a>
                      </li>
                      <li>
                        Yelp: <a href="https://www.yelp.com/biz/atx-cocina-austin?osq=ATX+Cocina">Yelp</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </>
          ) : (
            ''
          )}
        </a>

        <a style={{ position: 'absolute', bottom: 30, left: 30, fontSize: '13px' }} href="#" onClick={() => setLocation('/item/04')}>
          {params !== null && params.id === '04' ? (
            <>
              <div className="card-container">
                <div className="left-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">HAPPY HOUR</span>
                      <li>Come unwind with $2 off draft cocktails and beers</li>
                      <li>$1 off cans and bottles</li>
                      <li>$6 well drinks during our Happy Hour</li>
                      <li>3pm-7pm Mon-Thurs</li>
                      <li>Sun all day!</li>
                    </ul>
                  </div>
                </div>

                <div className="right-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Days w/Specials</span>
                      <li>Mon</li>
                      <li>Tue</li>
                      <li>Wed</li>
                      <li>Thu</li>
                      <li>Sun</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Additional Details</span>
                      <li>Data Source: Company Website</li>
                      <li>Source Date:</li>
                      <li>
                        Website: <a href="https://www.marriott.com/en-us/hotels/ausox-moxy-austin-university/dining/">Marriott Moxy Austin University</a>
                      </li>
                      <li>
                        Google Maps: <a href="https://maps.app.goo.gl/8VVwwvH3qGmr8tkm7">Google Maps</a>
                      </li>
                      <li>
                        Yelp: <a href="https://www.yelp.com/biz/bar-moxy-austin">Yelp</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </>
          ) : (
            ''
          )}
        </a>

        <a style={{ position: 'absolute', bottom: 30, left: 30, fontSize: '13px' }} href="#" onClick={() => setLocation('/item/04')}>
          {params !== null && params.id === '05' ? (
            <>
              <div className="card-container">
                <div className="left-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">EVERYDAY HAPPY HOUR (EVEN WEEKENDS)</span>
                      <li>3-6:30PM</li>
                      <li>$9 frozen cocktails</li>
                      <li>$9 cocktails on tap</li>
                      <li>$8 wine on tap</li>
                      <li>$3 off all appetizers</li>
                      <li>$1 off draft beer</li>
                      <li>Happy hour specials for dine-in and take-out</li>
                    </ul>
                  </div>
                </div>

                <div className="right-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Data Source</span>
                      <li>Company Website</li>
                      <li>Source Date:</li>
                      <li>
                        Website: <a href="https://www.hanksaustin.com/">Hank's Austin</a>
                      </li>
                      <li>
                        Google Maps: <a href="https://maps.app.goo.gl/QTm9TtRSGBsVA38t6">Google Maps</a>
                      </li>
                      <li>
                        Yelp: <a href="https://www.yelp.com/biz/hanks-austin-2">Yelp</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </>
          ) : (
            ''
          )}
        </a>

        <a style={{ position: 'absolute', bottom: 30, left: 30, fontSize: '13px' }} href="#" onClick={() => setLocation('/item/04')}>
          {params !== null && params.id === '06' ? (
            <>
              <div className="card-container">
                <div className="left-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">HAPPY HOUR</span>
                      <li>4-7 Daily</li>
                      <li>All Day Saturday</li>
                      <li>$3 Beer (Bottles & Cans)</li>
                      <li>$6 Bar Bites</li>
                      <li>Choose from: 1/4lb Dog, Onion Rings, Veggie Egg Rolls, Mozz Sticks</li>
                      <li>$9 classNameic Cocktails</li>
                      <li>$2 Off All Specialty Cocktails</li>
                    </ul>
                  </div>
                </div>

                <div className="right-column">
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Days w/Specials</span>
                      <li>Mon</li>
                      <li>Tue</li>
                      <li>Wed</li>
                      <li>Thu</li>
                      <li>Fri</li>
                      <li>Sat</li>
                      <li>Sun</li>
                    </ul>
                  </div>
                  <div className="card">
                    <ul>
                      <span className="cardTitle">Additional Details</span>
                      <li>Data Source: Social Media</li>
                      <li>Source Date: June 24, 2024</li>
                      <li>
                        Website: <a href="https://www.instagram.com/saturnatx">Instagram</a>
                      </li>
                      <li>
                        Google Maps: <a href="https://maps.app.goo.gl/V9rSxNvNtP8Dk33Y9">Google Maps</a>
                      </li>
                      <li>
                        Yelp: <a href="https://www.yelp.com/biz/saturn-austin">Yelp</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </>
          ) : (
            ''
          )}
        </a>
      </div>{' '}
    </>
  )
}

createRoot(document.getElementById('root')).render(<Root />)
